spring:
  main:
    web-application-type: SERVLET
  application:
    name: iservport-concurrency-spring
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: false
    generate-ddl: false
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  freemarker:
    prefer-file-system-access: false
    charset: UTF-8
    suffix: .ftl
